events {}
http {
    server {
        listen 8443;
        location / {
            # Proxy HTTP requests to the OIDC Discovery Provider's unix socket.
            proxy_pass http://unix:/run/oidc-discovery-provider/server.sock:;
        }
    }
}
